[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lxml>=6.0.2",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "pulp>=3.3.0",
    "requests>=2.32.5",
]
